In [1]:
import pandas as pd
import numpy as np
import difflib 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
#loading the data from the csv file to a pandas data frame
df=pd.read_csv(r"C:\Users\acer\Downloads\movie dataset\tmdb_5000_movies.csv")
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [3]:
#printing frst 5 rows of the df
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
#num of rows and columns in df
df.shape

(4803, 20)

In [5]:
#selected features
selected_features=['genres','keywords','tagline',]
print(selected_features)

['genres', 'keywords', 'tagline']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [7]:
#combining all the file selected feature
combined_features=df['genres']+' '+df['keywords']

In [8]:
print(combined_features)

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                [] []
4802    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4803, dtype: object

In [9]:
#converting the text to feature vectors
vectorizer=TfidfVectorizer()

In [10]:
feature_vectors=vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 121566 stored elements and shape (4803, 17024)>
  Coords	Values
  (0, 12909)	0.4103230480870884
  (0, 6914)	0.03959219544029483
  (0, 14065)	0.4103230480870884
  (0, 9887)	0.03940948469284516
  (0, 652)	0.04577189633579202
  (0, 9915)	0.045607624940676474
  (0, 920)	0.05591271509322377
  (0, 12112)	0.05527246314514244
  (0, 9526)	0.05212473557118873
  (0, 15381)	0.051912924768404006
  (0, 12170)	0.05200336451294274
  (0, 1012)	0.11050191787596107
  (0, 11410)	0.10152277878251244
  (0, 11041)	0.11050191787596107
  (0, 7007)	0.09151425773372934
  (0, 12360)	0.08467014386813172
  (0, 7395)	0.13677491690901591
  (0, 15763)	0.3207963717596308
  (0, 16797)	0.12276473954918746
  (0, 7404)	0.12294334521887536
  (0, 11125)	0.11414458732137263
  (0, 7631)	0.12294334521887536
  (0, 15717)	0.09763087805117776
  (0, 7688)	0.10352417980885618
  (0, 16432)	0.08089385022121291
  :	:
  (4800, 6742)	0.21865211991404457
  (4800, 11464)	0.20344145050587167
  (4800, 10197)	0.1876640480847484
  (4800, 8500)	0.17127502008082066
  (4800, 6691)	0.2112035687018821
  (4800, 14080)	0.20907264917280002
  (4800, 9156)	0.20907264917280002
  (4800, 15580)	0.20707930707663671
  (4800, 7445)	0.24300447909025996
  (4800, 282)	0.21865211991404457
  (4800, 3488)	0.2713051103407916
  (4800, 14714)	0.2713051103407916
  (4802, 12909)	0.22918412639113114
  (4802, 14065)	0.22918412639113114
  (4802, 11393)	0.2932622176137517
  (4802, 1282)	0.2627606343469334
  (4802, 14230)	0.2546344011993499
  (4802, 11757)	0.25192532203843604
  (4802, 12454)	0.24317712265330366
  (4802, 9854)	0.3151256752804331
  (4802, 9822)	0.2173554825358715
  (4802, 11692)	0.21456748796992747
  (4802, 6197)	0.32708670942835183
  (4802, 10752)	0.32708670942835183
  (4802, 445)	0.38197512898860164

In [12]:
#cosine similarity,getting the similarity scores using cosine similarity
similarity=cosine_similarity(feature_vectors)

In [13]:
print(similarity.shape)

(4803, 4803)

In [ ]:
#getting the movie name by user
movie_name=input("Enter your favourite movie name:")

Enter your favourite movie name: iron man

In [15]:
#create a list with all the movie names given in the dataset
list_of_all_titles=df['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [16]:
#finding the close match 
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [17]:
close_match=find_close_match[0]
print(close_match)

Iron Man

In [18]:
#find the index of the movie
index_of_the_movie=df[df.title==close_match].index[0]
print(index_of_the_movie)

68

In [20]:
#getting a list of similar movies
similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.2846435502017603)), (1, np.float64(0.2915065651178053)), (2, np.float64(0.25910949284640566)), (3, np.float64(0.30175526241638484)), (4, np.float64(0.2658677323181715)), (5, np.float64(0.35454400382943746)), (6, np.float64(0.22857603316641348)), (7, np.float64(0.5956682166089914)), (8, np.float64(0.22003290930383795)), (9, np.float64(0.3295517012153594)), (10, np.float64(0.34938510402564615)), (11, np.float64(0.259339301493897)), (12, np.float64(0.28629465172407315)), (13, np.float64(0.21694989009388452)), (14, np.float64(0.37327877504363377)), (15, np.float64(0.24283869389735735)), (16, np.float64(0.5950965202685431)), (17, np.float64(0.2881936436778593)), (18, np.float64(0.20908968682245724)), (19, np.float64(0.2483825379665962)), (20, np.float64(0.3010889354262292)), (21, np.float64(0.20744734470496315)), (22, np.float64(0.19795741250758483)), (23, np.float64(0.22690568818976958)), (24, np.float64(0.22785293148297603)), (25, np.float64(0.2497645048919285)), (26, np.float64(0.6070042091170407)), (27, np.float64(0.2705269677015387)), (28, np.float64(0.27292913004035574)), (29, np.float64(0.23798840446673775)), (30, np.float64(0.3692571288073027)), (31, np.float64(0.6842753949994551)), (32, np.float64(0.22953747053873685)), (33, np.float64(0.47469550898353746)), (34, np.float64(0.23128822224093637)), (35, np.float64(0.261979839463853)), (36, np.float64(0.2283059294990038)), (37, np.float64(0.22696897782597578)), (38, np.float64(0.39721396020946115)), (39, np.float64(0.24678513295916907)), (40, np.float64(0.2599212294261236)), (41, np.float64(0.28752275205325684)), (42, np.float64(0.20734887672994676)), (43, np.float64(0.2614546236765441)), (44, np.float64(0.17470516401046163)), (45, np.float64(0.2376273488197199)), (46, np.float64(0.43627459854196754)), (47, np.float64(0.2742312361159409)), (48, np.float64(0.2101729742509245)), (49, np.float64(0.2324534270671562)), (50, np.float64(0.22589894100906835)), (51, np.float64(0.26246503026650264)), (52, np.float64(0.26792165583310334)), (53, np.float64(0.22901302648389638)), (54, np.float64(0.2272413076573638)), (55, np.float64(0.29217796414551017)), (56, np.float64(0.24814107638687594)), (57, np.float64(0.1637596401776414)), (58, np.float64(0.23859638071759157)), (59, np.float64(0.2221395601839739)), (60, np.float64(0.21082444087946547)), (61, np.float64(0.27719393890596816)), (62, np.float64(0.19553438868662576)), (63, np.float64(0.25915542793881846)), (64, np.float64(0.44772496261537603)), (65, np.float64(0.32807414191970874)), (66, np.float64(0.21035503976236114)), (67, np.float64(0.2770476502160226)), (68, np.float64(1.0)), (69, np.float64(0.25275452734634957)), (70, np.float64(0.2654220693366773)), (71, np.float64(0.30498233992642093)), (72, np.float64(0.3156768460066174)), (73, np.float64(0.2378941496534611)), (74, np.float64(0.22887599321509)), (75, np.float64(0.22509115300700458)), (76, np.float64(0.30435588183177276)), (77, np.float64(0.24784907519549848)), (78, np.float64(0.26396465669578195)), (79, np.float64(0.7191162552703182)), (80, np.float64(0.2308626571981474)), (81, np.float64(0.23349005196925182)), (82, np.float64(0.28108503084103453)), (83, np.float64(0.37459582095177407)), (84, np.float64(0.2390166194051747)), (85, np.float64(0.566653290658485)), (86, np.float64(0.25124179907897926)), (87, np.float64(0.23089794846309306)), (88, np.float64(0.2802860732281685)), (89, np.float64(0.25500488064741206)), (90, np.float64(0.22838707487611376)), (91, np.float64(0.24746455178912088)), (92, np.float64(0.27772992999106305)), (93, np.float64(0.25347756076425876)), (94, np.float64(0.4919129993828744)), (95, np.float64(0.29238482674037014)), (96, np.float64(0.2769022916343883)), (97, np.float64(0.2521482651589528)), (98, np.float64(0.2710120098386853)), (99, np.float64(0.2583810406457125)), (100, np.float64(0.24373085694008784)), (101, np.float64(0.42173200534843397)), (102, np.float64(0.27149019087502085)), (103, np.float64(0.31802633320894674)), (104, np.float64(0.2618186295766272)), (105, np.float64(0.19143005864418397)), (106, np.float64(0.29527069944054646)), (107, np.float64(0.29811768966911256)), (108, np.float64(0.30469848047398174)), (109, np.float64(0.2253384968563726)), (110, np.float64(0.22899245559148693)), (111, np.float64(0.2772237801215957)), (112, np.float64(0.2572518921823103)), (113, np.float64(0.243206987594933)), (114, np.float64(0.24935574034739483)), (115, np.float64(0.2625082617938891)), (116, np.float64(0.25099712700368987)), (117, np.float64(0.24406956974063165)), (118, np.float64(0.25264588072050614)), (119, np.float64(0.3350055817702871)), (120, np.float64(0.2531530856798098)), (121, np.float64(0.2252023298440621)), (122, np.float64(0.48843597593849436)), (123, np.float64(0.3146079393379353)), (124, np.float64(0.2765140288503295)), (125, np.float64(0.31045727281867197)), (126, np.float64(0.5400731711402639)), (127, np.float64(0.277124521308715)), (128, np.float64(0.2260727275166751)), (129, np.float64(0.49105500356837223)), (130, np.float64(0.19972127286818797)), (131, np.float64(0.2701314199098623)), (132, np.float64(0.1937032140455495)), (133, np.float64(0.21542672123652332)), (134, np.float64(0.23582071558628223)), (135, np.float64(0.19999803990702966)), (136, np.float64(0.2579996467428148)), (137, np.float64(0.18827600896778915)), (138, np.float64(0.27304768540615926)), (139, np.float64(0.31215142713302835)), (140, np.float64(0.20972999575647666)), (141, np.float64(0.24763046879496897)), (142, np.float64(0.23164021969602253)), (143, np.float64(0.2150639026092433)), (144, np.float64(0.2605795339368259)), (145, np.float64(0.23092318279190774)), (146, np.float64(0.16010568840324238)), (147, np.float64(0.20989260917940308)), (148, np.float64(0.19294225967376333)), (149, np.float64(0.2789086560737172)), (150, np.float64(0.2650553585756926)), (151, np.float64(0.2381685780262929)), (152, np.float64(0.2637696449862376)), (153, np.float64(0.23958162733553917)), (154, np.float64(0.19352028079823913)), (155, np.float64(0.22349626005898748)), (156, np.float64(0.2937118272488787)), (157, np.float64(0.21618410252838322)), (158, np.float64(0.2478698762435144)), (159, np.float64(0.3286868893865973)), (160, np.float64(0.2709888406939153)), (161, np.float64(0.2000512978879604)), (162, np.float64(0.2177400512739618)), (163, np.float64(0.311860268094009)), (164, np.float64(0.2426491854107158)), (165, np.float64(0.366229576382496)), (166, np.float64(0.2962421467850617)), (167, np.float64(0.22758661989527462)), (168, np.float64(0.30194181487178506)), (169, np.float64(0.526508280313008)), (170, np.float64(0.2035819475169057)), (171, np.float64(0.14621198929498808)), (172, np.float64(0.22569701937409947)), (173, np.float64(0.2696449190213189)), (174, np.float64(0.5465435276601112)), (175, np.float64(0.24840709024255175)), (176, np.float64(0.28244403632578285)), (177, np.float64(0.20921020764414675)), (178, np.float64(0.2272448946137094)), (179, np.float64(0.22819660104760106)), (180, np.float64(0.3013315792035557)), (181, np.float64(0.28725380174558995)), (182, np.float64(0.6669827068644317)), (183, np.float64(0.32880845427165906)), (184, np.float64(0.23496237896109665)), (185, np.float64(0.24145092297764773)), (186, np.float64(0.2927732590612922)), (187, np.float64(0.25551345158577443)), (188, np.float64(0.2975439528486021)), (189, np.float64(0.19321463377121537)), (190, np.float64(0.21424785107585423)), (191, np.float64(0.26556727447984607)), (192, np.float64(0.20610546853671682)), (193, np.float64(0.3340387777634179)), (194, np.float64(0.17524824827156676)), (195, np.float64(0.2098811501203329)), (196, np.float64(0.28782188492602606)), (197, np.float64(0.24525505726156288)), (198, np.float64(0.23474979860697043)), (199, np.float64(0.2786076415072496)), (200, np.float64(0.2655719089847346)), (201, np.float64(0.24704350568690808)), (202, np.float64(0.2174426053599767)), (203, np.float64(0.539617793249228)), (204, np.float64(0.26416075277743284)), (205, np.float64(0.20950744475115815)), (206, np.float64(0.22316855886028683)), (207, np.float64(0.2652978002504952)), (208, np.float64(0.235100441943177)), (209, np.float64(0.22002363168699068)), (210, np.float64(0.24381240763381637)), (211, np.float64(0.20753184089895008)), (212, np.float64(0.2746604636646358)), (213, np.float64(0.2970089238964308)), (214, np.float64(0.16445571188180463)), (215, np.float64(0.39761247575337244)), (216, np.float64(0.2254776775646354)), (217, np.float64(0.29471347965109096)), (218, np.float64(0.20846056258644097)), (219, np.float64(0.2594250784528096)), (220, np.float64(0.24760428425610892)), (221, np.float64(0.23788331864234902)), (222, np.float64(0.252182282430442)), (223, np.float64(0.20752839026080117)), (224, np.float64(0.2665374453856262)), (225, np.float64(0.26329820726071107)), (226, np.float64(0.25233885452533666)), (227, np.float64(0.2452936703321703)), (228, np.float64(0.2619382065049209)), (229, np.float64(0.23983077088576088)), (230, np.float64(0.2630806712243041)), (231, np.float64(0.1996043051622008)), (232, np.float64(0.48775262917410056)), (233, np.float64(0.24341581264223575)), (234, np.float64(0.2890236701386625)), (235, np.float64(0.238547694987)), (236, np.float64(0.2128999633876168)), (237, np.float64(0.22099852478138937)), (238, np.float64(0.3841974001463843)), (239, np.float64(0.20750510798443636)), (240, np.float64(0.2643894547580054)), (241, np.float64(0.32897361337822917)), (242, np.float64(0.425979040827524)), (243, np.float64(0.26349976353325916)), (244, np.float64(0.18463620928841545)), (245, np.float64(0.2441479559434761)), (246, np.float64(0.2710511167133304)), (247, np.float64(0.15285642221634171)), (248, np.float64(0.25710124200395895)), (249, np.float64(0.280828277879218)), (250, np.float64(0.1809901631768546)), (251, np.float64(0.1685982779104089)), (252, np.float64(0.2915169962269832)), (253, np.float64(0.19749033338151448)), (254, np.float64(0.3132699910645176)), (255, np.float64(0.16763719014168924)), (256, np.float64(0.2516424767323031)), (257, np.float64(0.22059181813240014)), (258, np.float64(0.2155043594265861)), (259, np.float64(0.21445158535227996)), (260, np.float64(0.2783794027227937)), (261, np.float64(0.30464502950686906)), (262, np.float64(0.278701479237422)), (263, np.float64(0.2103420095435829)), (264, np.float64(0.16854187654285802)), (265, np.float64(0.2331894450161259)), (266, np.float64(0.29675627979823654)), (267, np.float64(0.21382757374862593)), (268, np.float64(0.23087768896932545)), (269, np.float64(0.2504448069105408)), (270, np.float64(0.2772134175064642)), (271, np.float64(0.27314081804182005)), (272, np.float64(0.1639997691128045)), (273, np.float64(0.2574212255055467)), (274, np.float64(0.25551028997677844)), (275, np.float64(0.24416578521391058)), (276, np.float64(0.2447731879241323)), (277, np.float64(0.23649240955627726)), (278, np.float64(0.2580437898480305)), (279, np.float64(0.2338582746419705)), (280, np.float64(0.1781457259927476)), (281, np.float64(0.25657567078979165)), (282, np.float64(0.2210870755239864)), (283, np.float64(0.199814072978113)), (284, np.float64(0.20005611723226055)), (285, np.float64(0.2319388632252267)), (286, np.float64(0.3404997861013458)), (287, np.float64(0.2756363476822361)), (288, np.float64(0.2630075954367641)), (289, np.float64(0.22465131573685168)), (290, np.float64(0.21637738425566236)), (291, np.float64(0.21944159958532233)), (292, np.float64(0.25351336167280847)), (293, np.float64(0.17454305129134579)), (294, np.float64(0.204487903622863)), (295, np.float64(0.2478646142312959)), (296, np.float64(0.29778598913565935)), (297, np.float64(0.23034524014726865)), (298, np.float64(0.23951120161633932)), (299, np.float64(0.2731545394740073)), (300, np.float64(0.27342005809537595)), (301, np.float64(0.2435630073078921)), (302, np.float64(0.2243015824904744)), (303, np.float64(0.22748779701366825)), (304, np.float64(0.196256370443046)), (305, np.float64(0.27516614145310886)), (306, np.float64(0.23374814972562738)), (307, np.float64(0.3259775882866614)), (308, np.float64(0.23797656334442455)), (309, np.float64(0.23022369358972633)), (310, np.float64(0.27572530790143335)), (311, np.float64(0.2445119948789588)), (312, np.float64(0.2073931059542282)), (313, np.float64(0.20454623869912752)), (314, np.float64(0.22021838471258484)), (315, np.float64(0.20320582272827675)), (316, np.float64(0.22426548921890252)), (317, np.float64(0.15540961871917575)), (318, np.float64(0.1952928358515389)), (319, np.float64(0.2333908629525007)), (320, np.float64(0.18630665220256157)), (321, np.float64(0.15378943003993786)), (322, np.float64(0.33539750049735445)), (323, np.float64(0.28462032745292765)), (324, np.float64(0.2305599918125704)), (325, np.float64(0.19538868954965333)), (326, np.float64(0.22991209347307223)), (327, np.float64(0.2389002472440156)), (328, np.float64(0.20957698393563556)), (329, np.float64(0.28152696052244847)), (330, np.float64(0.28023559644550083)), (331, np.float64(0.20025514317850598)), (332, np.float64(0.2203212207126228)), (333, np.float64(0.23968296595734676)), (334, np.float64(0.26115451863331024)), (335, np.float64(0.2416522682343009)), (336, np.float64(0.2013629143349783)), (337, np.float64(0.21156044572409313)), (338, np.float64(0.18388234371056303)), (339, np.float64(0.2947505042398547)), (340, np.float64(0.20889412838145244)), (341, np.float64(0.20282629089546036)), (342, np.float64(0.25248469735697404)), (343, np.float64(0.22093445838701928)), (344, np.float64(0.1516654762813743)), (345, np.float64(0.3105794181278537)), (346, np.float64(0.2151777080287946)), (347, np.float64(0.20210398241146943)), (348, np.float64(0.25564417452339533)), (349, np.float64(0.22752055102938573)), (350, np.float64(0.2911604790965419)), (351, np.float64(0.2211613586083092)), (352, np.float64(0.2312644413934086)), (353, np.float64(0.20188417816299825)), (354, np.float64(0.2649640341372192)), (355, np.float64(0.29562894835811265)), (356, np.float64(0.2433794887072981)), (357, np.float64(0.12012267409400398)), (358, np.float64(0.23097726221599546)), (359, np.float64(0.27204502208461306)), (360, np.float64(0.26226817087347765)), (361, np.float64(0.2892200745325907)), (362, np.float64(0.2274585265846074)), (363, np.float64(0.27852598201148976)), (364, np.float64(0.27816292635504)), (365, np.float64(0.2602246441449982)), (366, np.float64(0.24656712949430354)), (367, np.float64(0.22960106088112806)), (368, np.float64(0.206578082695009)), (369, np.float64(0.23879944179099227)), (370, np.float64(0.2782955181901814)), (371, np.float64(0.2573782396317886)), (372, np.float64(0.22442814178153744)), (373, np.float64(0.1934368920427413)), (374, np.float64(0.23976863295380357)), (375, np.float64(0.21226096598679112)), (376, np.float64(0.24331400629924466)), (377, np.float64(0.19417020758467346)), (378, np.float64(0.1835102463011339)), (379, np.float64(0.20262896025323257)), (380, np.float64(0.23371044194649587)), (381, np.float64(0.2580693924763664)), (382, np.float64(0.1589904433014637)), (383, np.float64(0.2384989309731313)), (384, np.float64(0.18019794510947976)), (385, np.float64(0.23904565553552906)), (386, np.float64(0.2760605741196813)), (387, np.float64(0.23215102214843455)), (388, np.float64(0.20420946326262907)), (389, np.float64(0.21159664218654978)), (390, np.float64(0.2632815960820152)), (391, np.float64(0.23789973020728974)), (392, np.float64(0.18978049999464822)), (393, np.float64(0.1718729420570776)), (394, np.float64(0.24142210610469633)), (395, np.float64(0.2217166323685766)), (396, np.float64(0.27794573756711594)), (397, np.float64(0.17866403858645716)), (398, np.float64(0.176347289501415)), (399, np.float64(0.22478753563065204)), (400, np.float64(0.2600269748203946)), (401, np.float64(0.14121449120613427)), (402, np.float64(0.22701913137942753)), (403, np.float64(0.23129015074940226)), (404, np.float64(0.19950113033296105)), (405, np.float64(0.1919557968082905)), (406, np.float64(0.24263928664498194)), (407, np.float64(0.20382966418319595)), (408, np.float64(0.22816420712066504)), (409, np.float64(0.21113635073041093)), (410, np.float64(0.27757754625739567)), (411, np.float64(0.22110039147949662)), (412, np.float64(0.21937379546091051)), (413, np.float64(0.23015367908867843)), (414, np.float64(0.18318597687520968)), (415, np.float64(0.34065392440050823)), (416, np.float64(0.2509837631988872)), (417, np.float64(0.28807586457795664)), (418, np.float64(0.2763362297203742)), (419, np.float64(0.260707789604757)), (420, np.float64(0.2634768551419528)), (421, np.float64(0.2515392326976613)), (422, np.float64(0.1869098154129896)), (423, np.float64(0.2286515167895707)), (424, np.float64(0.2727460131164493)), (425, np.float64(0.31059826802175816)), (426, np.float64(0.24856687427783725)), (427, np.float64(0.15496867033204573)), (428, np.float64(0.26231591474929156)), (429, np.float64(0.20883628252366165)), (430, np.float64(0.20000778728470656)), (431, np.float64(0.24723262534226723)), (432, np.float64(0.22533882126128776)), (433, np.float64(0.22956235225404015)), (434, np.float64(0.20314106668450937)), (435, np.float64(0.21085888865659105)), (436, np.float64(0.20283484762790982)), (437, np.float64(0.246268457106225)), (438, np.float64(0.20519967190315241)), (439, np.float64(0.22940621598339916)), (440, np.float64(0.21858624332138568)), (441, np.float64(0.25640625448349924)), (442, np.float64(0.29646964987396096)), (443, np.float64(0.176284047236722)), (444, np.float64(0.1836274980020824)), (445, np.float64(0.2012894483272168)), (446, np.float64(0.29033445422564397)), (447, np.float64(0.24514638489938076)), (448, np.float64(0.13457644057084775)), (449, np.float64(0.27320200425423896)), (450, np.float64(0.2096625680887975)), (451, np.float64(0.26270424703308254)), (452, np.float64(0.1875996273331439)), (453, np.float64(0.23762456147069747)), (454, np.float64(0.2670924969406509)), (455, np.float64(0.3028640341232343)), (456, np.float64(0.20497063925694875)), (457, np.float64(0.21778788079409137)), (458, np.float64(0.21552099162586538)), (459, np.float64(0.23781296698079987)), (460, np.float64(0.202434311842358)), (461, np.float64(0.20766750074036716)), (462, np.float64(0.2021205932010841)), (463, np.float64(0.17982925112584386)), (464, np.float64(0.2587508118433759)), (465, np.float64(0.15763775074968134)), (466, np.float64(0.2653171946884448)), (467, np.float64(0.23970509193473752)), (468, np.float64(0.2614113333413275)), (469, np.float64(0.24016658175099784)), (470, np.float64(0.20808724807911425)), (471, np.float64(0.18462766220673016)), (472, np.float64(0.30462716362550946)), (473, np.float64(0.22965173410513717)), (474, np.float64(0.23438671268731373)), (475, np.float64(0.23764118089533856)), (476, np.float64(0.26776030723657623)), (477, np.float64(0.16229227479274796)), (478, np.float64(0.271465896076929)), (479, np.float64(0.22709372047763307)), (480, np.float64(0.2479685443015229)), (481, np.float64(0.19413867593509035)), (482, np.float64(0.20276226394679317)), (483, np.float64(0.2141411263842121)), (484, np.float64(0.20341504055465814)), (485, np.float64(0.21438627242729053)), (486, np.float64(0.2106243371211177)), (487, np.float64(0.2508947458834351)), (488, np.float64(0.22275603190144422)), (489, np.float64(0.19149065437047072)), (490, np.float64(0.2886056436430898)), (491, np.float64(0.2485569296434149)), (492, np.float64(0.1887992649864348)), (493, np.float64(0.20978124076201007)), (494, np.float64(0.2026324452489401)), (495, np.float64(0.2611819054370077)), (496, np.float64(0.1982353224215731)), (497, np.float64(0.23049467070025592)), (498, np.float64(0.16079221525888013)), (499, np.float64(0.19460850825771095)), (500, np.float64(0.19866527523913505)), (501, np.float64(0.2887368979412973)), (502, np.float64(0.21133214623709426)), (503, np.float64(0.23242860178676847)), (504, np.float64(0.20103253110282424)), (505, np.float64(0.24146437550624045)), (506, np.float64(0.23189721352584602)), (507, np.float64(0.2712240387449111)), (508, np.float64(0.23375480170279223)), (509, np.

In [21]:
len(similarity_score)

4803

In [22]:
#sorting the movies based on their similarity score
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(68, np.float64(1.0)), (79, np.float64(0.7191162552703182)), (31, np.float64(0.6842753949994551)), (182, np.float64(0.6669827068644317)), (26, np.float64(0.6070042091170407)), (7, np.float64(0.5956682166089914)), (16, np.float64(0.5950965202685431)), (85, np.float64(0.566653290658485)), (174, np.float64(0.5465435276601112)), (126, np.float64(0.5400731711402639)), (203, np.float64(0.539617793249228)), (511, np.float64(0.5325130061672599)), (169, np.float64(0.526508280313008)), (94, np.float64(0.4919129993828744)), (129, np.float64(0.49105500356837223)), (122, np.float64(0.48843597593849436)), (232, np.float64(0.48775262917410056)), (33, np.float64(0.47469550898353746)), (788, np.float64(0.4603156565016041)), (64, np.float64(0.44772496261537603)), (46, np.float64(0.43627459854196754)), (1740, np.float64(0.4321720092326088)), (242, np.float64(0.425979040827524)), (101, np.float64(0.42173200534843397)), (2390, np.float64(0.4116998889419878)), (215, np.float64(0.39761247575337244)), (38, np.float64(0.39721396020946115)), (4033, np.float64(0.38620160131600034)), (1192, np.float64(0.38596963035301124)), (238, np.float64(0.3841974001463843)), (2317, np.float64(0.3809118747242736)), (674, np.float64(0.3764705564827444)), (3051, np.float64(0.3756924307652378)), (83, np.float64(0.37459582095177407)), (2442, np.float64(0.37331897431012034)), (14, np.float64(0.37327877504363377)), (1230, np.float64(0.3721835374774713)), (30, np.float64(0.3692571288073027)), (4487, np.float64(0.3690002256743144)), (3993, np.float64(0.36725036893254814)), (165, np.float64(0.366229576382496)), (4734, np.float64(0.3654734440490878)), (3437, np.float64(0.3630962952512167)), (813, np.float64(0.3626194085142785)), (1652, np.float64(0.3576192393675064)), (618, np.float64(0.3570180825266258)), (2708, np.float64(0.35521697984744716)), (5, np.float64(0.35454400382943746)), (1296, np.float64(0.3533501364622245)), (678, np.float64(0.3520734490383193)), (4143, np.float64(0.3520734490383193)), (4787, np.float64(0.35198611656465895)), (1324, np.float64(0.35052518583868064)), (10, np.float64(0.34938510402564615)), (4395, np.float64(0.3489387757806935)), (2122, np.float64(0.3449414481114817)), (3318, np.float64(0.34485411819602213)), (3087, np.float64(0.3447071284533204)), (4401, np.float64(0.34364339442778963)), (4450, np.float64(0.34364339442778963)), (1277, np.float64(0.3433734672196377)), (870, np.float64(0.34304047648247615)), (2681, np.float64(0.34275406193808255)), (654, np.float64(0.34222918168507344)), (2428, np.float64(0.3406583950425616)), (415, np.float64(0.34065392440050823)), (805, np.float64(0.34061946176647506)), (286, np.float64(0.3404997861013458)), (3361, np.float64(0.33935416475921304)), (3786, np.float64(0.33839718352280573)), (4117, np.float64(0.3360559600914027)), (1445, np.float64(0.33570301744376113)), (322, np.float64(0.33539750049735445)), (119, np.float64(0.3350055817702871)), (2156, np.float64(0.33437381914340386)), (193, np.float64(0.3340387777634179)), (1135, np.float64(0.3298868954092317)), (9, np.float64(0.3295517012153594)), (700, np.float64(0.3290671373925117)), (241, np.float64(0.32897361337822917)), (183, np.float64(0.32880845427165906)), (2217, np.float64(0.32877192197546967)), (159, np.float64(0.3286868893865973)), (1072, np.float64(0.3286622031622058)), (65, np.float64(0.32807414191970874)), (3373, np.float64(0.3277874924220837)), (3144, np.float64(0.3276788504062984)), (2899, np.float64(0.32646762176351685)), (545, np.float64(0.32607849061137595)), (2205, np.float64(0.32607352929445277)), (307, np.float64(0.3259775882866614)), (4251, np.float64(0.32549247297296674)), (4399, np.float64(0.3246649364261141)), (2577, np.float64(0.32462350596607126)), (3981, np.float64(0.32300144182857127)), (1358, np.float64(0.3227714317734271)), (1486, np.float64(0.32225419652981624)), (1986, np.float64(0.32210822294881924)), (3359, np.float64(0.32210822294881924)), (1667, np.float64(0.32207939939296193)), (1286, np.float64(0.32181062205113287)), (1133, np.float64(0.3212101218787507)), (1720, np.float64(0.32097894400774174)), (1269, np.float64(0.3209444382334532)), (2646, np.float64(0.3209444382334532)), (3020, np.float64(0.3209444382334532)), (3284, np.float64(0.3209444382334532)), (3299, np.float64(0.3209444382334532)), (3857, np.float64(0.3209444382334532)), (4111, np.float64(0.3209444382334532)), (4764, np.float64(0.32064782790711416)), (3225, np.float64(0.32004127677663097)), (660, np.float64(0.31920038418847313)), (4440, np.float64(0.31875041117989117)), (103, np.float64(0.31802633320894674)), (1103, np.float64(0.31575392016720366)), (72, np.float64(0.3156768460066174)), (2892, np.float64(0.315019324965583)), (123, np.float64(0.3146079393379353)), (3385, np.float64(0.31395545352609117)), (1267, np.float64(0.3137899778305357)), (1469, np.float64(0.3137899778305357)), (2728, np.float64(0.3137899778305357)), (3623, np.float64(0.3137899778305357)), (1956, np.float64(0.3134451666262653)), (1826, np.float64(0.31327120839975076)), (254, np.float64(0.3132699910645176)), (139, np.float64(0.31215142713302835)), (163, np.float64(0.311860268094009)), (1569, np.float64(0.3114332859125538)), (2380, np.float64(0.31075435375724747)), (2047, np.float64(0.3106220736272781)), (425, np.float64(0.31059826802175816)), (345, np.float64(0.3105794181278537)), (125, np.float64(0.31045727281867197)), (2827, np.float64(0.310181368334561)), (3089, np.float64(0.30993394238437694)), (1382, np.float64(0.3098862593853992)), (3154, np.float64(0.30976699255919543)), (2163, np.float64(0.30920413182279743)), (1200, np.float64(0.30886805467233736)), (1702, np.float64(0.30807099358024265)), (1517, np.float64(0.3078323728614939)), (1024, np.float64(0.30726452638722895)), (3639, np.float64(0.30682081726280636)), (71, np.float64(0.30498233992642093)), (108, np.float64(0.30469848047398174)), (261, np.float64(0.30464502950686906)), (472, np.float64(0.30462716362550946)), (2851, np.float64(0.30455553992584866)), (2069, np.float64(0.3045515625042424)), (76, np.float64(0.30435588183177276)), (4691, np.float64(0.3042929557978421)), (2933, np.float64(0.30426929413640796)), (3304, np.float64(0.30426929413640796)), (2590, np.float64(0.30393416083447594)), (539, np.float64(0.3037819674470858)), (2464, np.float64(0.30320726633148753)), (455, np.float64(0.3028640341232343)), (2823, np.float64(0.302204758150516)), (1695, np.float64(0.30206918886891676)), (4004, np.float64(0.3020085518753582)), (168, np.float64(0.30194181487178506)), (3, np.float64(0.30175526241638484)), (3326, np.float64(0.3016859627130038)), (4638, np.float64(0.3016859627130038)), (180, np.float64(0.3013315792035557)), (2346, np.float64(0.3010998953440957)), (20, np.float64(0.3010889354262292)), (4225, np.float64(0.3008432733412499)), (834, np.float64(0.3005272431896132)), (1748, np.float64(0.30009360243966643)), (3819, np.float64(0.29849070125454513)), (2221, np.float64(0.29844604689490417)), (594, np.float64(0.2982859060526415)), (107, np.float64(0.29811768966911256)), (4693, np.float64(0.29782028666539556)), (296, np.float64(0.29778598913565935)), (2410, np.float64(0.2975883687330456)), (1535, np.float64(0.29755704247248926)), (188, np.float64(0.2975439528486021)), (884, np.float64(0.2973971547117689)), (1271, np.float64(0.2971628403730121)), (677, np.float64(0.2971046025203712)), (213, np.float64(0.2970089238964308)), (4436, np.float64(0.29688477585599427)), (266, np.float64(0.29675627979823654)), (4499, np.float64(0.29671975674673473)), (873, np.float64(0.2966094741856767)), (2506, np.float64(0.2965551253313342)), (442, np.float64(0.29646964987396096)), (1761, np.float64(0.29639727263524)), (166, np.float64(0.2962421467850617)), (2292, np.float64(0.2960233334436992)), (1696, np.float64(0.29574924202313596)), (2222, np.float64(0.29572063192170095)), (2921, np.float64(0.29572063192170095)), (2931, np.float64(0.29572063192170095)), (2896, np.float64(0.2957122202383999)), (3718, np.float64(0.2957122202383999)), (355, np.float64(0.29562894835811265)), (3305, np.float64(0.2953577261302889)), (106, np.float64(0.29527069944054646)), (4104, np.float64(0.29510314658386755)), (3414, np.float64(0.29507327656435606)), (339, np.float64(0.2947505042398547)), (217, np.float64(0.29471347965109096)), (931, np.float64(0.29462282650093374)), (1537, np.float64(0.29438699559095416)), (4077, np.float64(0.29410024790384864)), (4160, np.float64(0.29404808829680545)), (156, np.float64(0.2937118272488787)), (782, np.float64(0.2935839291266912)), (3035, np.float64(0.29354210750877097)), (186, np.float64(0.2927732590612922)), (3416, np.float64(0.29256199759866464)), (95, np.float64(0.29238482674037014)), (981, np.float64(0.29231315695670584)), (1288, np.float64(0.29231315695670584)), (2001, np.float64(0.29231315695670584)), (2867, np.float64(0.29231315695670584)), (3500, np.float64(0.29231315695670584)), (3523, np.float64(0.29231315695670584)), (3836, np.float64(0.29231315695670584)), (3943, np.float64(0.29231315695670584)), (4546, np.float64(0.29231315695670584)), (2235, np.float64(0.2922731115083346)), (4230, np.float64(0.2922586704300648)), (55, np.float64(0.29217796414551017)), (1068, np.float64(0.29198109957009427)), (3368, np.float64(0.2919283399402566)), (784, np.float64(0.2917714104457754)), (3396, np.float64(0.29161097890398957)), (252, np.float64(0.2915169962269832)), (1, np.float64(0.2915065651178053)), (2389, np.float64(0.291241091681776)), (2644, np.float64(0.2912326357680912)), (350, np.float64(0.2911604790965419)), (696, np.float64(0.29084856954004984)), (1390, np.float64(0.2905414442871164)), (578, np.float64(0.29038669289501695)), (2264, np.float64(0.2903481715290254)), (446, np.float64(0.29033445422564397)), (2878, np.float64(0.29025667342520256)), (778, np.float64(0.2900242588400374)), (2046, np.float64(0.28996876007215194)), (3652, np.float64(0.2899462196170549)), (3948, np.float64(0.2899462196170549)), (4069, np.float64(0.2899462196170549)), (4522, np.float64(0.2897991777560809)), (1825, np.float64(0.28968075152493095)), (2642, np.float64(0.28958616775258067)), (1401, np.float64(0.28952343209230497)), (1433, np.float64(0.2893140927466971)), (361, np.float64(0.2892200745325907)), (234, np.float64(0.2890236701386625)), (1568, np.float64(0.2890207631971276)), (821, np.float64(0.2890089496056494)), (866, np.float64(0.2889138010172975)), (3306, np.float64(0.2889138010172975)), (3412, np.float64(0.2889138010172975)), (3591, np.float64(0.2889138010172975)), (3714, np.float64(0.2889138010172975)), (3972, np.float64(0.2889138010172975)), (4256, np.float64(0.2889138010172975)), (3856, np.float64(0.2888141058946884)), (3357, np.float64(0.288767003499128)), (1083, np.float64(0.28875227534136594)), (501, np.float64(0.2887368979412973)), (972, np.float64(0.2886234741842979)), (490, np.float64(0.2886056436430898)), (1635, np.float64(0.2885772684797064)), (1851, np.float64(0.2884519447344634)), (1056, np.float64(0.2883262871412887)), (1827, np.float64(0.28832038799182896)), (3351, np.float64(0.2882771483656056)), (17, np.float64(0.2881936436778593)), (3912, np.float64(0.2881619090666069)), (2853, np.float64(0.2881058991513571)), (3541, np.float64(0.28809350773500747)), (417, np.float64(0.28807586457795664)), (4262, np.float64(0.2878404373614564)), (2884, np.float64(0.2878287015879575)), (196, np.float64(0.28782188492602606)), (3746, np.float64(0.28762525692232144)), (41, np.float64(0.28752275205325684)), (668, np.float64(0.28725736879213437)), (181, np.float64(0.28725380174558995)), (2076, np.float64(0.2872478977771172)), (2758, np.float64(0.287083743777634)), (1973, np.float64(0.2869640698611572)), (941, np.float64(0.2869576221084421)), (1155, np.float64(0.28679778201114503)), (12, np.float64(0.28629465172407315)), (1189, np.float64(0.28604631757953597)), (1428, np.float64(0.28603894844723826)), (3379, np.float64(0.2859515545718645)), (2675, np.float64(0.28592602298743536)), (3230, np.float64(0.28590755299800535)), (3750, np.float64(0.2857605601733647)), (1001, np.float64(0.28573505635400864)), (3795, np.float64(0.285678253325196)), (3946, np.float64(0.28553528664978983)), (1613, np.float64(0.2855331825130281)), (3311, np.float64(0.2851960032128299)), (1733, np.float64(0.2849176251399109)), (2089, np.float64(0.28470769911078886)), (3143, np.float64(0.28467854428805783)), (0, np.float64(0.2846435502017603)), (323, np.float64(0.28462032745292765)), (1258, np.float64(0.28462032745292765)), (1692, np.float64(0.28462032745292765)), (2011, np.float64(0.28462032745292765)), (2081, np.float64(0.28462032745292765)), (2364, np.float64(0.28462032745292765)), (2611, np.float64(0.28462032745292765)), (2629, np.float64(0.28462032745292765)), (2963, np.float64(0.28462032745292765)), (3164, np.float64(0.28462032745292765)), (3264, np.float64(0.28462032745292765)), (3422, np.float64(0.28462032745292765)), (3453, np.float64(0.28462032745292765)), (3510, np.float64(0.28462032745292765)), (3528, np.float64(0.28462032745292765)), (4247, np.float64(0.28462032745292765)), (4417, np.float64(0.28462032745292765)), (673, np.float64(0.2845314596322536)), (1459, np.float64(0.2841426659690095)), (2196, np.float64(0.2841375047790715)), (4631, np.float64(0.2841142997434028)), (1079, np.float64(0.28400926202704707)), (945, np.float64(0.2839699104003015)), (2030, np.float64(0.28395546684844253)), (1395, np.float64(0.2839009987268475)), (3048, np.float64(0.2838611551037311)), (2063, np.float64(0.28379606385550843)), (4072, np.float64(0.2837333907385751)), (1143, np.float64(0.283699412576806)), (1077, np.float64(0.28366887920568895)), (3014, np.float64(0.283622860049907)), (2188, np.float64(0.28357290177225947)), (2858, np.float64(0.2834123278789689)), (2581, np.float64(0.2832515704747433)), (1086, np.float64(0.2828879845893752)), (4470, np.float64(0.28286570513017867)), (1586, np.float64(0.28284683075271605)), (2614, np.float64(0.2828190960539792)), (2145, np.float64(0.2827966666647544)), (553, np.float64(0.2827659001802048)), (1617, np.float64(0.28258898836105406)), (2824, np.float64(0.2825220794939099)), (3403, np.float64(0.2824553120967806)), (176, np.float64(0.28244403632578285)), (534, np.float64(0.2823717965584845)), (1902, np.float64(0.2820714710985621)), (969, np.float64(0.28195962494556964)), (848, np.float64(0.2819306221229)), (573, np.float64(0.28154446143003903)), (329, np.float64(0.28152696052244847)), (3575, np.float64(0.28122343569505115)), (3343, np.float64(0.28114493373717103)), (82, np.float64(0.28108503084103453)), (566, np.float64(0.2809093228658026)), (3423, np.float64(0.28086265060088356)), (249, np.float64(0.280828277879218)), (2879, np.float64(0.280744323904875)), (3631, np.float64(0.280696319482553)), (732, np.float64(0.2805247377660228)), (1089, np.float64(0.280480635324897)), (2250, np.float64(0.2803823071968396)), (2799, np.float64(0.2803337418072719)), (982, np.float64(0.28029459821544706)), (88, np.float64(0.2802860732281685)), (330, np.float64(0.28023559644550083)), (3336, np.float64(0.2801550836234643)), (4233, np.float64(0.2801529360255737)), (4258, np.float64(0.2801529360255737)), (1165, np.float64(0.280057462988566)), (1670, np.float64(0.279867794964535)), (776, np.float64(0.2798134331209022)), (4157, np.float64(0.27973871104896536)), (4688, np.float64(0.27964980291528957)), (1932, np.float64(0.2796171845533193)), (799, np.float64(0.2795359989831987)), (1099, np.float64(0.27949732656562165)), (3021, np.float64(0.27949732656562165)), (3509, np.float64(0.27949732656562165)), (4161, np.float64(0.27949732656562165)), (149, np.float64(0.2789086560737172)), (952, np.float64(0.27871487305675735)), (1100, np.float64(0.2787102381442922)), (262, np.float64(0.278701479237422)), (737, np.float64(0.27868745217403035)), (702, np.float64(0.2786181823138236)), (199, np.float64(0.2786076415072496)), (645, np.float64(0.27853635564977647)), (363, np.float64(0.27852598201148976)), (3251, np.float64(0.27851713871396666)), (260, np.float64(0.2783794027227937)), (370, np.float64(0.2782955181901814)), (2932, np.float64(0.2782404680509276)), (4476, np.float64(0.2782404680509276)), (364, np.float64(0.27816292635504)), (1205, np.float64(0.27809741695415374)), (3204, np.float64(0.27797773755592337)), (396, np.float64(0.27794573756711594)), (950, np.float64(0.2779036926017614)), (3941, np.float64(0.2778788614932062)), (92, np.float64(0.27772992999106305)), (410, np.float64(0.27757754625739567)), (983, np.float64(0.27746577858819027)), (1831, np.float64(0.2774640354357967)), (2157, np.float64(0.27742159822550083)), (111, np.float64(0.2772237801215957)), (1427, np.float64(0.27722346548847693)), (270, np.float64(0.2772134175064642)), (61, np.float64(0.27719393890596816)), (770, np.float64(0.2771322415465264)), (3873, np.float64(0.27712996137336393)), (127, np.float64(0.277124521308715)), (67, np.float64(0.2770476502160226)), (2941, np.float64(0.2769748773088726)), (3315, np.float64(0.27694685262188057)), (96, np.float64(0.2769022916343883)), (2433, np.float64(0.2768567935205028)), (2640, np.float64(0.27678797895115315)), (2110, np.float64(0.2766576802347201)), (1342, np.float64(0.2766428367736088)), (510, np.float64(0.27659058725856867)), (3290, np.float64(0.2765447266170589)), (124, np.float64(0.2765140288503295)), (1127, np.float64(0.27649956658589125)), (956, np.float64(0.27640210971549084)), (418, np.float64(0.2763362297203742)), (1096, np.float64(0.27607032338644133)), (386, np.float64(0.2760605741196813)), (530, np.float64(0.27587726977307536)), (1294, np.float64(0.27583855095764187)), (543, np.float64(0.27576455458338617)), (310, np.float64(0.27572530790143335)), (1319, np.float64(0.27567294943916165)), (4372, np.float64(0.2756571392020978)), (287, np.float64(0.2756363476822361)), (911, np.float64(0.27557808031855224)), (1596, np.float64(0.27556200973269357)), (694, np.float64(0.27544989778544166)), (600, np.float64(0.27536248161289895)), (305, np.float64(0.27516614145310886)), (1422, np.float64(0.2751605543417443)), (516, np.float64(0.27514044027971385)), (2045, np.float64(0.2751358586896314)), (3011, np.float64(0.2748889002477746)), (212, np.float64(0.2746604636646358)), (2531, np.float64(0.27444452727660096)), (2634, np.float64(0.27444452727660096)), (2869, np.float64(0.27444452727660096)), (2970, np.float64(0.27444452727660096)), (3080, np.float64(0.27444452727660096)), (3166, np.float64(0.27444452727660096)), (3194, np.float64(0.27444452727660096)), (3669, np.float64(0.27444452727660096)), (3674, np.float64(0.27444452727660096)), (3798, np.float64(0.27444452727660096)), (3967, np.float64(0.27444452727660096)), (4086, np.float64(0.27444452727660096)), (4252, np.float64(0.27444452727660096)), (4543, np.float64(0.27444452727660096)), (4646, np.float64(0.27444452727660096)), (1425, np.float64(0.2742382070074066)), (47, np.float64(0.2742312361159409)), (4128, np.float64(0.27422495812714137)), (1384, np.float64(0.2739370118988647)), (2348, np.float64(0.27392097135963334)), (1847, np.float64(0.27373209129591347)), (2881, np.float64(0.27362991143930065)), (940, np.float64(0.2735220268208349)), (300, np.float64(0.27342005809537595)), (1106, np.float64(0.2733011265552502)), (947, np.float64(0.2732978071236636)), (449, np.float64(0.27320200425423896)), (740, np.float64(0.2731865461892984)), (299, np.float64(0.2731545394740073)), (271, np.float64(0.27314081804182005)), (138, np.float64(0.27304768540615926)), (2826, np.float64(0.27302603925655183)), (28, np.float64(0.27292913004035574)), (424, np.float64(0.2727460131164493)), (2136, np.float64(0.27273386852516707)), (1968, np.float64(0.2725369461596541)), (1203, np.float64(0.27250423746398084)), (755, np.float64(0.27248072754484537)), (2493, np.float64(0.27227050593280483)), (634, np.float64(0.2720920534641924)), (359, np.float64(0.27204502208461306)), (606, np.float64(0.27204312484014903)), (2181, np.float64(0.27183302592990843)), (3756, np.float64(0.27181919871244997)), (1872, np.float64(0.2717157123401294)), (546, np.float64(0.27170081404108026)), (1844, np.float64(0.27168279688302177)), (3699, np.float64(0.2716057

In [28]:
#print the similar movies based on the index
print("Movies suggested for you:\n ")
i=1
for movie in sorted_similar_movies:
    index=movie[0]
    title_from_index=df[df.index==index]['title'].values[0]
    if(i<21):
        print(i,'.',title_from_index)
        i+=1

Movies suggested for you:

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Ant-Man
5 . Captain America: Civil War
6 . Avengers: Age of Ultron
7 . The Avengers
8 . Captain America: The Winter Soldier
9 . The Incredible Hulk
10 . Thor: The Dark World
11 . X2
12 . X-Men
13 . Captain America: The First Avenger
14 . Guardians of the Galaxy
15 . Thor
16 . X-Men Origins: Wolverine
17 . The Wolverine
18 . X-Men: The Last Stand
19 . Deadpool
20 . X-Men: Apocalypse

In [30]:
#MOVIES RECOMMENDATION SYSTEM

movie_name=input("Enter your favourite movie name:")

list_of_all_titles=df['title'].tolist()

find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)

close_match=find_close_match[0]

index_of_the_movie=df[df.title==close_match].index[0]

similarity_score=list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)

print("Movies suggested for you:\n ")
i=1
for movie in sorted_similar_movies:
    index=movie[0]
    title_from_index=df[df.index==index]['title'].values[0]
    if(i<21):
        print(i,'.',title_from_index)
        i+=1

Enter your favourite movie name: avatar

Movies suggested for you:

1 . Avatar
2 . Star Trek Into Darkness
3 . Alien³
4 . Planet of the Apes
5 . Aliens
6 . Alien
7 . Titan A.E.
8 . Silent Running
9 . Treasure Planet
10 . The Astronaut's Wife
11 . Jupiter Ascending
12 . Soldier
13 . The Fifth Element
14 . Meet Dave
15 . Moonraker
16 . Armageddon
17 . Jonah: A VeggieTales Movie
18 . Starship Troopers
19 . Cargo
20 . Interstellar